# Site settings
title: Randy Tolentino | One Seven
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Collections
# collections:
#     some-collection:
#         output: true

# Build settings
markdown: kramdown
