# Site settings
title: Randy Tolentino | One Seven
description: >
  Randy Tolentino is a family man - happily married and the father of two. He enjoys family dates, writing code, sewing things, and is comfortable with making mistakes. Randy works for CIO organization at IBM, under the AgileAcademy domain.
keywords: "Randy Tolentino, Front End Developer, hip hop artist, Son of Ran, IBM, Design, Code"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Collections
# collections:
#     some-collection:
#         output: true

# Build settings
markdown: kramdown
