# Site settings
title: Randy Tolentino | Chapter Four
theme: fourfold
heading: unfolding
subheading: the narrative
description: >
  Every day feels like a fresh start.
keywords: "Randy Tolentino, Front End Developer, hip hop artist, Son of Ran, Design, Code"

# Collections
collections:
  dev:
    output: true
    permalink: /:collection/:path
    layout: page
  fam:
    output: true
    permalink: /:collection/:path
    layout: page
  maker:
    output: true
    permalink: /:collection/:path
    layout: page

# Build settings
markdown: kramdown
