# Site settings
title: Randy Tolentino
email: makertolentino@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: ""
url: ""

sass:
    style: compressed

# Build settings
markdown: kramdown
