---
# Site settings
title: Randy Tolentino | Fourfold
concept: '||||'
heading: unfolding
subheading: the narrative
description: |
  This story was never my own, although years back I used to think so. As a husband and as a father, I've come to realize that this entire thing has a higher purpose.

  This collection of writings aims to document and convey my understandings through a fourfold lens
keywords: "Randy Tolentino, Front End Developer, hip hop artist, Son of Ran, Design, Code"

# Collections
collections:
  entries:
    output: true
    permalink: /blog/:path
    layout: page

# Build settings
markdown: kramdown
---
