# Site settings
title: Randy Tolentino | Chapter Four
description: >
  Randy Tolentino is a family man - happily married and the father of two. He enjoys family dates, wood working, writing code, sewing things, and design.
keywords: "Randy Tolentino, Front End Developer, hip hop artist, Son of Ran, Design, Code"

# Collections
collections:
  blog:
    output: true
    permalink: /:collection/:path
    layout: page

# Build settings
markdown: kramdown
