---
# Site settings
title: Randy Tolentino | These Worlds Within Me
description: |
  This story was never my own, although years back I used to think so. As a husband and as a father, I've come to realize that this entire experience has a higher purpose.

  This collection of writings is meant to document and convey the failures, learnings, and understandings of this life as I know it.
keywords: "Randy Tolentino, Front End Developer, hip hop artist, Son of Ran, Design, Code"

# Collections
collections:
  entries:
    output: true
    permalink: /blog/:path
    layout: page

# Build settings
markdown: kramdown
---
